# Generated by Django 2.1.5 on 2019-07-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='categories',
        ),
    ]
